[package]
name = "rust_heart_disease_predictor"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.1"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
plotters = "0.3"
ndarray = "0.15"
